package com.example.lingoFlix.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a dynamic capability generated by the Skill Builder.
 * A "Skill" can be a new game mode, a translation tool, or a custom automation.
 */
@Entity(tableName = "dynamic_skills")
data class DynamicSkill(
    @PrimaryKey val id: String,
    val name: String,
    val description: String,
    val iconName: String = "AutoFixNormal", // Default icon
    val category: String = "General",
    
    // The "Logic" of the skill. 
    // This could be a specialized prompt for an LLM, a set of action steps, 
    // or a JSON representation of a workflow.
    val logicInstructions: String,
    
    // Metadata for the generator
    val version: Int = 1,
    val createdAt: Long = System.currentTimeMillis(),
    val isEnabled: Boolean = true
)
